Upgrade to Scala.js 1.0.0-M7.
scala-js/scala-js-env-phantomjs pull request #27
Opened 2019-04-09 14:34 UTC by sjrd

2019-04-09 15:42 UTC, gzm0 requested changes
This should set exitJSStatement now: https://github.com/scala-js/scala-js/blob/master/js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/JSEnvSuiteConfig.scala#L62

2019-04-09 15:42 UTC, gzm0 commented on phantomjs-env/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala
> +  }
can we consolidate this with `inputFiles` somewhow?

2019-04-13 14:10 UTC, sjrd commented
Updated to follow the design of https://github.com/scala-js/scala-js-env-jsdom-nodejs/pull/20

2019-04-13 14:58 UTC, gzm0 approved these changes

2019-04-13 16:36 UTC, merged